package com.example.upc.dataobject;

import java.util.Date;

public class ExamSubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject.id
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject.industry
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    private Integer industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject.work_type
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    private Integer workType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject.qualified_score
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    private Float qualifiedScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject.total_score
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    private Float totalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject.exam_time
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    private Integer examTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject.operate_time
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject.operator
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject.operator_ip
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    private String operatorIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject.id
     *
     * @return the value of exam_subject.id
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject.id
     *
     * @param id the value for exam_subject.id
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject.industry
     *
     * @return the value of exam_subject.industry
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public Integer getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject.industry
     *
     * @param industry the value for exam_subject.industry
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public void setIndustry(Integer industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject.work_type
     *
     * @return the value of exam_subject.work_type
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public Integer getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject.work_type
     *
     * @param workType the value for exam_subject.work_type
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public void setWorkType(Integer workType) {
        this.workType = workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject.qualified_score
     *
     * @return the value of exam_subject.qualified_score
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public Float getQualifiedScore() {
        return qualifiedScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject.qualified_score
     *
     * @param qualifiedScore the value for exam_subject.qualified_score
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public void setQualifiedScore(Float qualifiedScore) {
        this.qualifiedScore = qualifiedScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject.total_score
     *
     * @return the value of exam_subject.total_score
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public Float getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject.total_score
     *
     * @param totalScore the value for exam_subject.total_score
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public void setTotalScore(Float totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject.exam_time
     *
     * @return the value of exam_subject.exam_time
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public Integer getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject.exam_time
     *
     * @param examTime the value for exam_subject.exam_time
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public void setExamTime(Integer examTime) {
        this.examTime = examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject.operate_time
     *
     * @return the value of exam_subject.operate_time
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject.operate_time
     *
     * @param operateTime the value for exam_subject.operate_time
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject.operator
     *
     * @return the value of exam_subject.operator
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject.operator
     *
     * @param operator the value for exam_subject.operator
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject.operator_ip
     *
     * @return the value of exam_subject.operator_ip
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject.operator_ip
     *
     * @param operatorIp the value for exam_subject.operator_ip
     *
     * @mbg.generated Mon May 13 21:07:23 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }
}