package com.example.upc.dataobject;

import java.util.Date;

public class ExamSubjectTopic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject_topic.id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject_topic.subject_id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject_topic.topic_id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Integer topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject_topic.operator
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject_topic.operate_time
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_subject_topic.operate_ip
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject_topic.id
     *
     * @return the value of exam_subject_topic.id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject_topic.id
     *
     * @param id the value for exam_subject_topic.id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject_topic.subject_id
     *
     * @return the value of exam_subject_topic.subject_id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject_topic.subject_id
     *
     * @param subjectId the value for exam_subject_topic.subject_id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject_topic.topic_id
     *
     * @return the value of exam_subject_topic.topic_id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject_topic.topic_id
     *
     * @param topicId the value for exam_subject_topic.topic_id
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject_topic.operator
     *
     * @return the value of exam_subject_topic.operator
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject_topic.operator
     *
     * @param operator the value for exam_subject_topic.operator
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject_topic.operate_time
     *
     * @return the value of exam_subject_topic.operate_time
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject_topic.operate_time
     *
     * @param operateTime the value for exam_subject_topic.operate_time
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_subject_topic.operate_ip
     *
     * @return the value of exam_subject_topic.operate_ip
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_subject_topic.operate_ip
     *
     * @param operateIp the value for exam_subject_topic.operate_ip
     *
     * @mbg.generated Mon Apr 29 10:58:28 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}