package com.example.upc.dataobject;

import java.util.Date;

public class FormatOriginRecordEx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.id
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.enterprise
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private Integer enterprise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.area
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.origin_type
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String originType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.record_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.origin_name
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String originName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.origin_type_ex
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String originTypeEx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.producer
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String producer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.brand
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.net_content
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String netContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.produce_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private Date produceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.keep_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String keepTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.dead_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private Date deadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.goods_in
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private Float goodsIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.goods_type
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.supplier
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.supplier_type
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String supplierType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.goods_out
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private Float goodsOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.goods
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private Float goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.state
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.person
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.document
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String document;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.operator
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.operator_ip
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column format_origin_record_ex.operator_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.id
     *
     * @return the value of format_origin_record_ex.id
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.id
     *
     * @param id the value for format_origin_record_ex.id
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.enterprise
     *
     * @return the value of format_origin_record_ex.enterprise
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public Integer getEnterprise() {
        return enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.enterprise
     *
     * @param enterprise the value for format_origin_record_ex.enterprise
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setEnterprise(Integer enterprise) {
        this.enterprise = enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.area
     *
     * @return the value of format_origin_record_ex.area
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.area
     *
     * @param area the value for format_origin_record_ex.area
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.origin_type
     *
     * @return the value of format_origin_record_ex.origin_type
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getOriginType() {
        return originType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.origin_type
     *
     * @param originType the value for format_origin_record_ex.origin_type
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setOriginType(String originType) {
        this.originType = originType == null ? null : originType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.record_time
     *
     * @return the value of format_origin_record_ex.record_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.record_time
     *
     * @param recordTime the value for format_origin_record_ex.record_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.origin_name
     *
     * @return the value of format_origin_record_ex.origin_name
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getOriginName() {
        return originName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.origin_name
     *
     * @param originName the value for format_origin_record_ex.origin_name
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setOriginName(String originName) {
        this.originName = originName == null ? null : originName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.origin_type_ex
     *
     * @return the value of format_origin_record_ex.origin_type_ex
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getOriginTypeEx() {
        return originTypeEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.origin_type_ex
     *
     * @param originTypeEx the value for format_origin_record_ex.origin_type_ex
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setOriginTypeEx(String originTypeEx) {
        this.originTypeEx = originTypeEx == null ? null : originTypeEx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.producer
     *
     * @return the value of format_origin_record_ex.producer
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getProducer() {
        return producer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.producer
     *
     * @param producer the value for format_origin_record_ex.producer
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setProducer(String producer) {
        this.producer = producer == null ? null : producer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.brand
     *
     * @return the value of format_origin_record_ex.brand
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.brand
     *
     * @param brand the value for format_origin_record_ex.brand
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.net_content
     *
     * @return the value of format_origin_record_ex.net_content
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getNetContent() {
        return netContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.net_content
     *
     * @param netContent the value for format_origin_record_ex.net_content
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setNetContent(String netContent) {
        this.netContent = netContent == null ? null : netContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.produce_time
     *
     * @return the value of format_origin_record_ex.produce_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public Date getProduceTime() {
        return produceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.produce_time
     *
     * @param produceTime the value for format_origin_record_ex.produce_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setProduceTime(Date produceTime) {
        this.produceTime = produceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.keep_time
     *
     * @return the value of format_origin_record_ex.keep_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getKeepTime() {
        return keepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.keep_time
     *
     * @param keepTime the value for format_origin_record_ex.keep_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setKeepTime(String keepTime) {
        this.keepTime = keepTime == null ? null : keepTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.dead_time
     *
     * @return the value of format_origin_record_ex.dead_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public Date getDeadTime() {
        return deadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.dead_time
     *
     * @param deadTime the value for format_origin_record_ex.dead_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setDeadTime(Date deadTime) {
        this.deadTime = deadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.goods_in
     *
     * @return the value of format_origin_record_ex.goods_in
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public Float getGoodsIn() {
        return goodsIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.goods_in
     *
     * @param goodsIn the value for format_origin_record_ex.goods_in
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setGoodsIn(Float goodsIn) {
        this.goodsIn = goodsIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.goods_type
     *
     * @return the value of format_origin_record_ex.goods_type
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.goods_type
     *
     * @param goodsType the value for format_origin_record_ex.goods_type
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.supplier
     *
     * @return the value of format_origin_record_ex.supplier
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.supplier
     *
     * @param supplier the value for format_origin_record_ex.supplier
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.supplier_type
     *
     * @return the value of format_origin_record_ex.supplier_type
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getSupplierType() {
        return supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.supplier_type
     *
     * @param supplierType the value for format_origin_record_ex.supplier_type
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setSupplierType(String supplierType) {
        this.supplierType = supplierType == null ? null : supplierType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.goods_out
     *
     * @return the value of format_origin_record_ex.goods_out
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public Float getGoodsOut() {
        return goodsOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.goods_out
     *
     * @param goodsOut the value for format_origin_record_ex.goods_out
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setGoodsOut(Float goodsOut) {
        this.goodsOut = goodsOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.goods
     *
     * @return the value of format_origin_record_ex.goods
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public Float getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.goods
     *
     * @param goods the value for format_origin_record_ex.goods
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setGoods(Float goods) {
        this.goods = goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.state
     *
     * @return the value of format_origin_record_ex.state
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.state
     *
     * @param state the value for format_origin_record_ex.state
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.person
     *
     * @return the value of format_origin_record_ex.person
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.person
     *
     * @param person the value for format_origin_record_ex.person
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.document
     *
     * @return the value of format_origin_record_ex.document
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getDocument() {
        return document;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.document
     *
     * @param document the value for format_origin_record_ex.document
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setDocument(String document) {
        this.document = document == null ? null : document.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.operator
     *
     * @return the value of format_origin_record_ex.operator
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.operator
     *
     * @param operator the value for format_origin_record_ex.operator
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.operator_ip
     *
     * @return the value of format_origin_record_ex.operator_ip
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.operator_ip
     *
     * @param operatorIp the value for format_origin_record_ex.operator_ip
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column format_origin_record_ex.operator_time
     *
     * @return the value of format_origin_record_ex.operator_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column format_origin_record_ex.operator_time
     *
     * @param operatorTime the value for format_origin_record_ex.operator_time
     *
     * @mbg.generated Fri Oct 25 10:27:54 CST 2019
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}