package com.example.upc.dataobject;

import java.util.Date;

public class ImportEnterprisePoints {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_enterprise_points.id
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_enterprise_points.enterprise_id
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_enterprise_points.business_state
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    private Integer businessState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_enterprise_points.point
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    private String point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_enterprise_points.operate_time
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_enterprise_points.operator
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_enterprise_points.operate_ip
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_enterprise_points.id
     *
     * @return the value of import_enterprise_points.id
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_enterprise_points.id
     *
     * @param id the value for import_enterprise_points.id
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_enterprise_points.enterprise_id
     *
     * @return the value of import_enterprise_points.enterprise_id
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_enterprise_points.enterprise_id
     *
     * @param enterpriseId the value for import_enterprise_points.enterprise_id
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_enterprise_points.business_state
     *
     * @return the value of import_enterprise_points.business_state
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public Integer getBusinessState() {
        return businessState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_enterprise_points.business_state
     *
     * @param businessState the value for import_enterprise_points.business_state
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public void setBusinessState(Integer businessState) {
        this.businessState = businessState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_enterprise_points.point
     *
     * @return the value of import_enterprise_points.point
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_enterprise_points.point
     *
     * @param point the value for import_enterprise_points.point
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public void setPoint(String point) {
        this.point = point == null ? null : point.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_enterprise_points.operate_time
     *
     * @return the value of import_enterprise_points.operate_time
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_enterprise_points.operate_time
     *
     * @param operateTime the value for import_enterprise_points.operate_time
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_enterprise_points.operator
     *
     * @return the value of import_enterprise_points.operator
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_enterprise_points.operator
     *
     * @param operator the value for import_enterprise_points.operator
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_enterprise_points.operate_ip
     *
     * @return the value of import_enterprise_points.operate_ip
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_enterprise_points.operate_ip
     *
     * @param operateIp the value for import_enterprise_points.operate_ip
     *
     * @mbg.generated Thu Dec 03 21:04:25 CST 2020
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}