package com.example.upc.dataobject;

import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotNull;
import java.util.Date;

public class StartSelfInspection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_self_inspection.id
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_self_inspection.enterprise
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    private Integer enterprise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_self_inspection.position_area
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    private String positionArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_self_inspection.inspector
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    private String inspector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_self_inspection.inspect_time
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @NotNull(message = "日期不能为空")
    private Date inspectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_self_inspection.position_catch
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    private String positionCatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_self_inspection.picture
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_self_inspection.operator
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_self_inspection.operator_ip
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_self_inspection.operator_time
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_self_inspection.id
     *
     * @return the value of start_self_inspection.id
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_self_inspection.id
     *
     * @param id the value for start_self_inspection.id
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_self_inspection.enterprise
     *
     * @return the value of start_self_inspection.enterprise
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public Integer getEnterprise() {
        return enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_self_inspection.enterprise
     *
     * @param enterprise the value for start_self_inspection.enterprise
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public void setEnterprise(Integer enterprise) {
        this.enterprise = enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_self_inspection.position_area
     *
     * @return the value of start_self_inspection.position_area
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public String getPositionArea() {
        return positionArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_self_inspection.position_area
     *
     * @param positionArea the value for start_self_inspection.position_area
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public void setPositionArea(String positionArea) {
        this.positionArea = positionArea == null ? null : positionArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_self_inspection.inspector
     *
     * @return the value of start_self_inspection.inspector
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public String getInspector() {
        return inspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_self_inspection.inspector
     *
     * @param inspector the value for start_self_inspection.inspector
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public void setInspector(String inspector) {
        this.inspector = inspector == null ? null : inspector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_self_inspection.inspect_time
     *
     * @return the value of start_self_inspection.inspect_time
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public Date getInspectTime() {
        return inspectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_self_inspection.inspect_time
     *
     * @param inspectTime the value for start_self_inspection.inspect_time
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public void setInspectTime(Date inspectTime) {
        this.inspectTime = inspectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_self_inspection.position_catch
     *
     * @return the value of start_self_inspection.position_catch
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public String getPositionCatch() {
        return positionCatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_self_inspection.position_catch
     *
     * @param positionCatch the value for start_self_inspection.position_catch
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public void setPositionCatch(String positionCatch) {
        this.positionCatch = positionCatch == null ? null : positionCatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_self_inspection.picture
     *
     * @return the value of start_self_inspection.picture
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_self_inspection.picture
     *
     * @param picture the value for start_self_inspection.picture
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_self_inspection.operator
     *
     * @return the value of start_self_inspection.operator
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_self_inspection.operator
     *
     * @param operator the value for start_self_inspection.operator
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_self_inspection.operator_ip
     *
     * @return the value of start_self_inspection.operator_ip
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_self_inspection.operator_ip
     *
     * @param operatorIp the value for start_self_inspection.operator_ip
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_self_inspection.operator_time
     *
     * @return the value of start_self_inspection.operator_time
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_self_inspection.operator_time
     *
     * @param operatorTime the value for start_self_inspection.operator_time
     *
     * @mbg.generated Sun Sep 06 21:01:46 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}