package com.example.upc.dataobject;

import java.util.Date;

public class SupervisionCa {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.id
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.company_id
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.company_name
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.name
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.id_number
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.sexy
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private Integer sexy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.telephone
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.work_type
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private Integer workType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.industry
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private Integer industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.electronic_number
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String electronicNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.health
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String health;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.train
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String train;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.education
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.health_number
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String healthNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.start_time
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.end_time
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.issuing_authority
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String issuingAuthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.photo
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.operate_time
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.operator
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_ca.operate_ip
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.id
     *
     * @return the value of supervision_ca.id
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.id
     *
     * @param id the value for supervision_ca.id
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.company_id
     *
     * @return the value of supervision_ca.company_id
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.company_id
     *
     * @param companyId the value for supervision_ca.company_id
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.company_name
     *
     * @return the value of supervision_ca.company_name
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.company_name
     *
     * @param companyName the value for supervision_ca.company_name
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.name
     *
     * @return the value of supervision_ca.name
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.name
     *
     * @param name the value for supervision_ca.name
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.id_number
     *
     * @return the value of supervision_ca.id_number
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.id_number
     *
     * @param idNumber the value for supervision_ca.id_number
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.sexy
     *
     * @return the value of supervision_ca.sexy
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public Integer getSexy() {
        return sexy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.sexy
     *
     * @param sexy the value for supervision_ca.sexy
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setSexy(Integer sexy) {
        this.sexy = sexy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.telephone
     *
     * @return the value of supervision_ca.telephone
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.telephone
     *
     * @param telephone the value for supervision_ca.telephone
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.work_type
     *
     * @return the value of supervision_ca.work_type
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public Integer getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.work_type
     *
     * @param workType the value for supervision_ca.work_type
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setWorkType(Integer workType) {
        this.workType = workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.industry
     *
     * @return the value of supervision_ca.industry
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public Integer getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.industry
     *
     * @param industry the value for supervision_ca.industry
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setIndustry(Integer industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.electronic_number
     *
     * @return the value of supervision_ca.electronic_number
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getElectronicNumber() {
        return electronicNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.electronic_number
     *
     * @param electronicNumber the value for supervision_ca.electronic_number
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setElectronicNumber(String electronicNumber) {
        this.electronicNumber = electronicNumber == null ? null : electronicNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.health
     *
     * @return the value of supervision_ca.health
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.health
     *
     * @param health the value for supervision_ca.health
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setHealth(String health) {
        this.health = health == null ? null : health.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.train
     *
     * @return the value of supervision_ca.train
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getTrain() {
        return train;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.train
     *
     * @param train the value for supervision_ca.train
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setTrain(String train) {
        this.train = train == null ? null : train.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.education
     *
     * @return the value of supervision_ca.education
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.education
     *
     * @param education the value for supervision_ca.education
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.health_number
     *
     * @return the value of supervision_ca.health_number
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getHealthNumber() {
        return healthNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.health_number
     *
     * @param healthNumber the value for supervision_ca.health_number
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setHealthNumber(String healthNumber) {
        this.healthNumber = healthNumber == null ? null : healthNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.start_time
     *
     * @return the value of supervision_ca.start_time
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.start_time
     *
     * @param startTime the value for supervision_ca.start_time
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.end_time
     *
     * @return the value of supervision_ca.end_time
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.end_time
     *
     * @param endTime the value for supervision_ca.end_time
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.issuing_authority
     *
     * @return the value of supervision_ca.issuing_authority
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getIssuingAuthority() {
        return issuingAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.issuing_authority
     *
     * @param issuingAuthority the value for supervision_ca.issuing_authority
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setIssuingAuthority(String issuingAuthority) {
        this.issuingAuthority = issuingAuthority == null ? null : issuingAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.photo
     *
     * @return the value of supervision_ca.photo
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.photo
     *
     * @param photo the value for supervision_ca.photo
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.operate_time
     *
     * @return the value of supervision_ca.operate_time
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.operate_time
     *
     * @param operateTime the value for supervision_ca.operate_time
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.operator
     *
     * @return the value of supervision_ca.operator
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.operator
     *
     * @param operator the value for supervision_ca.operator
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_ca.operate_ip
     *
     * @return the value of supervision_ca.operate_ip
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_ca.operate_ip
     *
     * @param operateIp the value for supervision_ca.operate_ip
     *
     * @mbg.generated Tue Jul 16 11:12:50 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}