package com.example.upc.dataobject;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

public class SupervisionEnFoodPro {
    private Integer id;
    private Integer enterpriseId;
    @NotBlank(message = "证号不能为空")
    private String number;
    @NotNull(message = "发证日期不能为空")
    private Date giveTime;
    @NotNull(message = "开始日期不能为空")
    private Date startTime;
    @NotNull(message = "结束日期不能为空")
    private Date endTime;
    @NotBlank(message = "发证机关不能为空")
    private String licenseAuthority;
    private Float validityAge;
    private String others;
    private String operator;
    private String operatorIp;
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.id
     *
     * @return the value of supervision_en_food_pro.id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.id
     *
     * @param id the value for supervision_en_food_pro.id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.enterprise_id
     *
     * @return the value of supervision_en_food_pro.enterprise_id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.enterprise_id
     *
     * @param enterpriseId the value for supervision_en_food_pro.enterprise_id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.number
     *
     * @return the value of supervision_en_food_pro.number
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.number
     *
     * @param number the value for supervision_en_food_pro.number
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.give_time
     *
     * @return the value of supervision_en_food_pro.give_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getGiveTime() {
        return giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.give_time
     *
     * @param giveTime the value for supervision_en_food_pro.give_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setGiveTime(Date giveTime) {
        this.giveTime = giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.start_time
     *
     * @return the value of supervision_en_food_pro.start_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.start_time
     *
     * @param startTime the value for supervision_en_food_pro.start_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.end_time
     *
     * @return the value of supervision_en_food_pro.end_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.end_time
     *
     * @param endTime the value for supervision_en_food_pro.end_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.license_authority
     *
     * @return the value of supervision_en_food_pro.license_authority
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getLicenseAuthority() {
        return licenseAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.license_authority
     *
     * @param licenseAuthority the value for supervision_en_food_pro.license_authority
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setLicenseAuthority(String licenseAuthority) {
        this.licenseAuthority = licenseAuthority == null ? null : licenseAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.validity_age
     *
     * @return the value of supervision_en_food_pro.validity_age
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Float getValidityAge() {
        return validityAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.validity_age
     *
     * @param validityAge the value for supervision_en_food_pro.validity_age
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setValidityAge(Float validityAge) {
        this.validityAge = validityAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.others
     *
     * @return the value of supervision_en_food_pro.others
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.others
     *
     * @param others the value for supervision_en_food_pro.others
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.operator
     *
     * @return the value of supervision_en_food_pro.operator
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.operator
     *
     * @param operator the value for supervision_en_food_pro.operator
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.operator_ip
     *
     * @return the value of supervision_en_food_pro.operator_ip
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.operator_ip
     *
     * @param operatorIp the value for supervision_en_food_pro.operator_ip
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_pro.operator_time
     *
     * @return the value of supervision_en_food_pro.operator_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_pro.operator_time
     *
     * @param operatorTime the value for supervision_en_food_pro.operator_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}