package com.example.upc.dataobject;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

public class SupervisionEnDrugsBu {
    private Integer id;
    private Integer enterpriseId;
    @NotBlank(message = "证号不能为空")
    private String number;
    private String qualityPerson;
    private String operationMode;
    private String warehouseAddress;
    @NotNull(message = "发证日期不能为空")
    private Date giveTime;
    @NotNull(message = "开始日期不能为空")
    private Date startTime;
    @NotNull(message = "结束日期不能为空")
    private Date endTime;
    private String gspNumber;
    private Date gspStartTime;
    private Date gspFinishTime;
    private Float validityTime;
    @NotBlank(message = "发证机关不能为空")
    private String licenseAuthority;
    private String businessScope;
    private String remark;
    private String operator;
    private String operatorIp;
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.id
     *
     * @return the value of supervision_en_drugs_bu.id
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.id
     *
     * @param id the value for supervision_en_drugs_bu.id
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.enterprise_id
     *
     * @return the value of supervision_en_drugs_bu.enterprise_id
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.enterprise_id
     *
     * @param enterpriseId the value for supervision_en_drugs_bu.enterprise_id
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.number
     *
     * @return the value of supervision_en_drugs_bu.number
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.number
     *
     * @param number the value for supervision_en_drugs_bu.number
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.quality_person
     *
     * @return the value of supervision_en_drugs_bu.quality_person
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public String getQualityPerson() {
        return qualityPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.quality_person
     *
     * @param qualityPerson the value for supervision_en_drugs_bu.quality_person
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setQualityPerson(String qualityPerson) {
        this.qualityPerson = qualityPerson == null ? null : qualityPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.operation_mode
     *
     * @return the value of supervision_en_drugs_bu.operation_mode
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public String getOperationMode() {
        return operationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.operation_mode
     *
     * @param operationMode the value for supervision_en_drugs_bu.operation_mode
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setOperationMode(String operationMode) {
        this.operationMode = operationMode == null ? null : operationMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.warehouse_address
     *
     * @return the value of supervision_en_drugs_bu.warehouse_address
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public String getWarehouseAddress() {
        return warehouseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.warehouse_address
     *
     * @param warehouseAddress the value for supervision_en_drugs_bu.warehouse_address
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setWarehouseAddress(String warehouseAddress) {
        this.warehouseAddress = warehouseAddress == null ? null : warehouseAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.give_time
     *
     * @return the value of supervision_en_drugs_bu.give_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public Date getGiveTime() {
        return giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.give_time
     *
     * @param giveTime the value for supervision_en_drugs_bu.give_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setGiveTime(Date giveTime) {
        this.giveTime = giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.start_time
     *
     * @return the value of supervision_en_drugs_bu.start_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.start_time
     *
     * @param startTime the value for supervision_en_drugs_bu.start_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.end_time
     *
     * @return the value of supervision_en_drugs_bu.end_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.end_time
     *
     * @param endTime the value for supervision_en_drugs_bu.end_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.gsp_number
     *
     * @return the value of supervision_en_drugs_bu.gsp_number
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public String getGspNumber() {
        return gspNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.gsp_number
     *
     * @param gspNumber the value for supervision_en_drugs_bu.gsp_number
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setGspNumber(String gspNumber) {
        this.gspNumber = gspNumber == null ? null : gspNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.gsp_start_time
     *
     * @return the value of supervision_en_drugs_bu.gsp_start_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public Date getGspStartTime() {
        return gspStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.gsp_start_time
     *
     * @param gspStartTime the value for supervision_en_drugs_bu.gsp_start_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setGspStartTime(Date gspStartTime) {
        this.gspStartTime = gspStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.gsp_finish_time
     *
     * @return the value of supervision_en_drugs_bu.gsp_finish_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public Date getGspFinishTime() {
        return gspFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.gsp_finish_time
     *
     * @param gspFinishTime the value for supervision_en_drugs_bu.gsp_finish_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setGspFinishTime(Date gspFinishTime) {
        this.gspFinishTime = gspFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.validity_time
     *
     * @return the value of supervision_en_drugs_bu.validity_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public Float getValidityTime() {
        return validityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.validity_time
     *
     * @param validityTime the value for supervision_en_drugs_bu.validity_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setValidityTime(Float validityTime) {
        this.validityTime = validityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.license_authority
     *
     * @return the value of supervision_en_drugs_bu.license_authority
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public String getLicenseAuthority() {
        return licenseAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.license_authority
     *
     * @param licenseAuthority the value for supervision_en_drugs_bu.license_authority
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setLicenseAuthority(String licenseAuthority) {
        this.licenseAuthority = licenseAuthority == null ? null : licenseAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.business_scope
     *
     * @return the value of supervision_en_drugs_bu.business_scope
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.business_scope
     *
     * @param businessScope the value for supervision_en_drugs_bu.business_scope
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.remark
     *
     * @return the value of supervision_en_drugs_bu.remark
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.remark
     *
     * @param remark the value for supervision_en_drugs_bu.remark
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.operator
     *
     * @return the value of supervision_en_drugs_bu.operator
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.operator
     *
     * @param operator the value for supervision_en_drugs_bu.operator
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.operator_ip
     *
     * @return the value of supervision_en_drugs_bu.operator_ip
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.operator_ip
     *
     * @param operatorIp the value for supervision_en_drugs_bu.operator_ip
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_drugs_bu.operator_time
     *
     * @return the value of supervision_en_drugs_bu.operator_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_drugs_bu.operator_time
     *
     * @param operatorTime the value for supervision_en_drugs_bu.operator_time
     *
     * @mbg.generated Tue Jul 16 23:08:26 CST 2019
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}