package com.example.upc.dataobject;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

public class SupervisionEnFoodBu {
    private Integer id;
    private Integer enterpriseId;
    @NotBlank(message = "食品经营证号不能为空")
    private String number;
    @NotBlank(message = "食品经营核定主体业态不能为空")
    private String businessFormat;
    private String businessNotes;
    private String isInternet;
    private String website;
    private String isReal;
    @NotBlank(message = "食品经营核定经营项目不能为空")
    private String businessProject;
    @NotNull(message = "发证日期不能为空")
    private Date giveTime;
    @NotNull(message = "开始日期日期不能为空")
    private Date startTime;
    @NotNull(message = "结束日期日期不能为空")
    private Date endTime;
    private Float validityAge;
    @NotBlank(message = "类别不能为空")
    private String category;
    @NotBlank(message = "发证机关不能为空")
    private String licenseAuthority;
    private String remark;
    private String operator;
    private String operateIp;
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.id
     *
     * @return the value of supervision_en_food_bu.id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.id
     *
     * @param id the value for supervision_en_food_bu.id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.enterprise_id
     *
     * @return the value of supervision_en_food_bu.enterprise_id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.enterprise_id
     *
     * @param enterpriseId the value for supervision_en_food_bu.enterprise_id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.number
     *
     * @return the value of supervision_en_food_bu.number
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.number
     *
     * @param number the value for supervision_en_food_bu.number
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.business_format
     *
     * @return the value of supervision_en_food_bu.business_format
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getBusinessFormat() {
        return businessFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.business_format
     *
     * @param businessFormat the value for supervision_en_food_bu.business_format
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setBusinessFormat(String businessFormat) {
        this.businessFormat = businessFormat == null ? null : businessFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.business_notes
     *
     * @return the value of supervision_en_food_bu.business_notes
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getBusinessNotes() {
        return businessNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.business_notes
     *
     * @param businessNotes the value for supervision_en_food_bu.business_notes
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setBusinessNotes(String businessNotes) {
        this.businessNotes = businessNotes == null ? null : businessNotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.is_internet
     *
     * @return the value of supervision_en_food_bu.is_internet
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getIsInternet() {
        return isInternet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.is_internet
     *
     * @param isInternet the value for supervision_en_food_bu.is_internet
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setIsInternet(String isInternet) {
        this.isInternet = isInternet == null ? null : isInternet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.website
     *
     * @return the value of supervision_en_food_bu.website
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.website
     *
     * @param website the value for supervision_en_food_bu.website
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.is_real
     *
     * @return the value of supervision_en_food_bu.is_real
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getIsReal() {
        return isReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.is_real
     *
     * @param isReal the value for supervision_en_food_bu.is_real
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setIsReal(String isReal) {
        this.isReal = isReal == null ? null : isReal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.business_project
     *
     * @return the value of supervision_en_food_bu.business_project
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getBusinessProject() {
        return businessProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.business_project
     *
     * @param businessProject the value for supervision_en_food_bu.business_project
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setBusinessProject(String businessProject) {
        this.businessProject = businessProject == null ? null : businessProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.give_time
     *
     * @return the value of supervision_en_food_bu.give_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getGiveTime() {
        return giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.give_time
     *
     * @param giveTime the value for supervision_en_food_bu.give_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setGiveTime(Date giveTime) {
        this.giveTime = giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.start_time
     *
     * @return the value of supervision_en_food_bu.start_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.start_time
     *
     * @param startTime the value for supervision_en_food_bu.start_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.end_time
     *
     * @return the value of supervision_en_food_bu.end_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.end_time
     *
     * @param endTime the value for supervision_en_food_bu.end_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.validity_age
     *
     * @return the value of supervision_en_food_bu.validity_age
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Float getValidityAge() {
        return validityAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.validity_age
     *
     * @param validityAge the value for supervision_en_food_bu.validity_age
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setValidityAge(Float validityAge) {
        this.validityAge = validityAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.category
     *
     * @return the value of supervision_en_food_bu.category
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.category
     *
     * @param category the value for supervision_en_food_bu.category
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.license_authority
     *
     * @return the value of supervision_en_food_bu.license_authority
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getLicenseAuthority() {
        return licenseAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.license_authority
     *
     * @param licenseAuthority the value for supervision_en_food_bu.license_authority
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setLicenseAuthority(String licenseAuthority) {
        this.licenseAuthority = licenseAuthority == null ? null : licenseAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.remark
     *
     * @return the value of supervision_en_food_bu.remark
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.remark
     *
     * @param remark the value for supervision_en_food_bu.remark
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.operator
     *
     * @return the value of supervision_en_food_bu.operator
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.operator
     *
     * @param operator the value for supervision_en_food_bu.operator
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.operate_ip
     *
     * @return the value of supervision_en_food_bu.operate_ip
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.operate_ip
     *
     * @param operateIp the value for supervision_en_food_bu.operate_ip
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_food_bu.operate_time
     *
     * @return the value of supervision_en_food_bu.operate_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_food_bu.operate_time
     *
     * @param operateTime the value for supervision_en_food_bu.operate_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}