package com.example.upc.dataobject;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

public class SupervisionEnCosmetics {
    private Integer id;
    private Integer enterpriseId;
    @NotBlank(message = "登记号不能为空")
    private String registerCode;
    private Float validityAge;
    @NotBlank(message = "发证机关不能为空")
    private String licenseAuthority;
    private String warehouse;
    @NotNull(message = "发证日期不能为空")
    private Date giveTime;
    @NotNull(message = "开始日期不能为空")
    private Date startTime;
    @NotNull(message = "结束日期不能为空")
    private Date endTime;
    private String licenseProject;
    private String remark;
    private Date operateTime;
    private String operator;
    private String operateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.id
     *
     * @return the value of supervision_en_cosmetics.id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.id
     *
     * @param id the value for supervision_en_cosmetics.id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.enterprise_id
     *
     * @return the value of supervision_en_cosmetics.enterprise_id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.enterprise_id
     *
     * @param enterpriseId the value for supervision_en_cosmetics.enterprise_id
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.register_code
     *
     * @return the value of supervision_en_cosmetics.register_code
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getRegisterCode() {
        return registerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.register_code
     *
     * @param registerCode the value for supervision_en_cosmetics.register_code
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setRegisterCode(String registerCode) {
        this.registerCode = registerCode == null ? null : registerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.validity_age
     *
     * @return the value of supervision_en_cosmetics.validity_age
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Float getValidityAge() {
        return validityAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.validity_age
     *
     * @param validityAge the value for supervision_en_cosmetics.validity_age
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setValidityAge(Float validityAge) {
        this.validityAge = validityAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.license_authority
     *
     * @return the value of supervision_en_cosmetics.license_authority
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getLicenseAuthority() {
        return licenseAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.license_authority
     *
     * @param licenseAuthority the value for supervision_en_cosmetics.license_authority
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setLicenseAuthority(String licenseAuthority) {
        this.licenseAuthority = licenseAuthority == null ? null : licenseAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.warehouse
     *
     * @return the value of supervision_en_cosmetics.warehouse
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getWarehouse() {
        return warehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.warehouse
     *
     * @param warehouse the value for supervision_en_cosmetics.warehouse
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse == null ? null : warehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.give_time
     *
     * @return the value of supervision_en_cosmetics.give_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getGiveTime() {
        return giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.give_time
     *
     * @param giveTime the value for supervision_en_cosmetics.give_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setGiveTime(Date giveTime) {
        this.giveTime = giveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.start_time
     *
     * @return the value of supervision_en_cosmetics.start_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.start_time
     *
     * @param startTime the value for supervision_en_cosmetics.start_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.end_time
     *
     * @return the value of supervision_en_cosmetics.end_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.end_time
     *
     * @param endTime the value for supervision_en_cosmetics.end_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.license_project
     *
     * @return the value of supervision_en_cosmetics.license_project
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getLicenseProject() {
        return licenseProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.license_project
     *
     * @param licenseProject the value for supervision_en_cosmetics.license_project
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setLicenseProject(String licenseProject) {
        this.licenseProject = licenseProject == null ? null : licenseProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.remark
     *
     * @return the value of supervision_en_cosmetics.remark
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.remark
     *
     * @param remark the value for supervision_en_cosmetics.remark
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.operate_time
     *
     * @return the value of supervision_en_cosmetics.operate_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.operate_time
     *
     * @param operateTime the value for supervision_en_cosmetics.operate_time
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.operator
     *
     * @return the value of supervision_en_cosmetics.operator
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.operator
     *
     * @param operator the value for supervision_en_cosmetics.operator
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_en_cosmetics.operate_ip
     *
     * @return the value of supervision_en_cosmetics.operate_ip
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public String getOperateIp() {
        return operateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_en_cosmetics.operate_ip
     *
     * @param operateIp the value for supervision_en_cosmetics.operate_ip
     *
     * @mbg.generated Mon Jul 01 11:33:32 CST 2019
     */
    public void setOperateIp(String operateIp) {
        this.operateIp = operateIp == null ? null : operateIp.trim();
    }
}