package com.example.upc.dataobject;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.validation.constraints.NotNull;
import java.util.Date;

public class SupervisionEnterpriseCredit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_enterprise_credit.id
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */

    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_enterprise_credit.enterprise_id
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_enterprise_credit.violation_date
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    @NotNull(message = "违规日期不能为空")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date violationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_enterprise_credit.violation_title
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    @NotNull(message = "违规标题不能为空")
    private String violationTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_enterprise_credit.violation_type
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    @NotNull(message = "违规类型不能为空")
    private String violationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_enterprise_credit.agent_person
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    @NotNull(message = "执法人员不能为空")
    private String agentPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_enterprise_credit.enclosure
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    private String enclosure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_enterprise_credit.operator
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_enterprise_credit.operator_ip
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_enterprise_credit.operator_time
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_enterprise_credit.id
     *
     * @return the value of supervision_enterprise_credit.id
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_enterprise_credit.id
     *
     * @param id the value for supervision_enterprise_credit.id
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_enterprise_credit.enterprise_id
     *
     * @return the value of supervision_enterprise_credit.enterprise_id
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_enterprise_credit.enterprise_id
     *
     * @param enterpriseId the value for supervision_enterprise_credit.enterprise_id
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_enterprise_credit.violation_date
     *
     * @return the value of supervision_enterprise_credit.violation_date
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public Date getViolationDate() {
        return violationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_enterprise_credit.violation_date
     *
     * @param violationDate the value for supervision_enterprise_credit.violation_date
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public void setViolationDate(Date violationDate) {
        this.violationDate = violationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_enterprise_credit.violation_title
     *
     * @return the value of supervision_enterprise_credit.violation_title
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public String getViolationTitle() {
        return violationTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_enterprise_credit.violation_title
     *
     * @param violationTitle the value for supervision_enterprise_credit.violation_title
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public void setViolationTitle(String violationTitle) {
        this.violationTitle = violationTitle == null ? null : violationTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_enterprise_credit.violation_type
     *
     * @return the value of supervision_enterprise_credit.violation_type
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public String getViolationType() {
        return violationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_enterprise_credit.violation_type
     *
     * @param violationType the value for supervision_enterprise_credit.violation_type
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public void setViolationType(String violationType) {
        this.violationType = violationType == null ? null : violationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_enterprise_credit.agent_person
     *
     * @return the value of supervision_enterprise_credit.agent_person
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public String getAgentPerson() {
        return agentPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_enterprise_credit.agent_person
     *
     * @param agentPerson the value for supervision_enterprise_credit.agent_person
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public void setAgentPerson(String agentPerson) {
        this.agentPerson = agentPerson == null ? null : agentPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_enterprise_credit.enclosure
     *
     * @return the value of supervision_enterprise_credit.enclosure
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public String getEnclosure() {
        return enclosure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_enterprise_credit.enclosure
     *
     * @param enclosure the value for supervision_enterprise_credit.enclosure
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public void setEnclosure(String enclosure) {
        this.enclosure = enclosure == null ? null : enclosure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_enterprise_credit.operator
     *
     * @return the value of supervision_enterprise_credit.operator
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_enterprise_credit.operator
     *
     * @param operator the value for supervision_enterprise_credit.operator
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_enterprise_credit.operator_ip
     *
     * @return the value of supervision_enterprise_credit.operator_ip
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_enterprise_credit.operator_ip
     *
     * @param operatorIp the value for supervision_enterprise_credit.operator_ip
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_enterprise_credit.operator_time
     *
     * @return the value of supervision_enterprise_credit.operator_time
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_enterprise_credit.operator_time
     *
     * @param operatorTime the value for supervision_enterprise_credit.operator_time
     *
     * @mbg.generated Mon Nov 30 20:50:04 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}