package com.example.upc.dao;

import com.example.upc.dataobject.FormatLeaveMainCourse;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FormatLeaveMainCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_main_course
     *
     * @mbg.generated Fri Jul 12 11:03:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_main_course
     *
     * @mbg.generated Fri Jul 12 11:03:17 CST 2019
     */
    int insert(FormatLeaveMainCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_main_course
     *
     * @mbg.generated Fri Jul 12 11:03:17 CST 2019
     */
    int insertSelective(FormatLeaveMainCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_main_course
     *
     * @mbg.generated Fri Jul 12 11:03:17 CST 2019
     */
    FormatLeaveMainCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_main_course
     *
     * @mbg.generated Fri Jul 12 11:03:17 CST 2019
     */
    int updateByPrimaryKeySelective(FormatLeaveMainCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table format_leave_main_course
     *
     * @mbg.generated Fri Jul 12 11:03:17 CST 2019
     */
    int updateByPrimaryKey(FormatLeaveMainCourse record);
    List<FormatLeaveMainCourse> selectByParentId(@Param("id") int id);
    void deleteByParentId(@Param("parentId") int parentId);
    void batchInsert(@Param("formatLeaveMainCourseList") List<FormatLeaveMainCourse> formatLeaveMainCourseList);
}