package com.example.upc.dao;

import com.example.upc.controller.param.MonthlySelfCheckParam;
import com.example.upc.dataobject.MonthlyAdditionalAnswer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MonthlyAdditionalAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_additional_answer
     *
     * @mbg.generated Mon Oct 12 16:53:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_additional_answer
     *
     * @mbg.generated Mon Oct 12 16:53:11 CST 2020
     */
    int insert(MonthlyAdditionalAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_additional_answer
     *
     * @mbg.generated Mon Oct 12 16:53:11 CST 2020
     */
    int insertSelective(MonthlyAdditionalAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_additional_answer
     *
     * @mbg.generated Mon Oct 12 16:53:11 CST 2020
     */
    MonthlyAdditionalAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_additional_answer
     *
     * @mbg.generated Mon Oct 12 16:53:11 CST 2020
     */
    int updateByPrimaryKeySelective(MonthlyAdditionalAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_additional_answer
     *
     * @mbg.generated Mon Oct 12 16:53:11 CST 2020
     */
    int updateByPrimaryKey(MonthlyAdditionalAnswer record);

    void deleteBySelfCheckId(@Param("selfCheckParam") MonthlySelfCheckParam monthlySelfCheckParam);

    MonthlyAdditionalAnswer selectBySelfCheckId(@Param("selfCheckId") Integer selfCheckId);
}