package com.example.upc.dao;

import com.example.upc.dataobject.UserEnterpriseVote;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.Map;
@Repository
@Mapper
public interface UserEnterpriseVoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise_vote
     *
     * @mbg.generated Tue Aug 18 16:05:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise_vote
     *
     * @mbg.generated Tue Aug 18 16:05:38 CST 2020
     */
    int insert(UserEnterpriseVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise_vote
     *
     * @mbg.generated Tue Aug 18 16:05:38 CST 2020
     */
    int insertSelective(UserEnterpriseVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise_vote
     *
     * @mbg.generated Tue Aug 18 16:05:38 CST 2020
     */
    UserEnterpriseVote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise_vote
     *
     * @mbg.generated Tue Aug 18 16:05:38 CST 2020
     */
    int updateByPrimaryKeySelective(UserEnterpriseVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise_vote
     *
     * @mbg.generated Tue Aug 18 16:05:38 CST 2020
     */
    int updateByPrimaryKey(UserEnterpriseVote record);

    Map<String,Object> selectVotesByEPId(int enterpriseId);
}